In [23]:
import pandas as pd
import numpy as np
import re
import string
import nltk

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [24]:
import os

print(os.listdir('/content'))

['.config', 'processed_sms_dataset.csv', 'Assignment17_NLP_Preprocessing.ipynb', '.ipynb_checkpoints', 'spam.csv', 'sample_data']

In [25]:
df = pd.read_csv("/content/spam.csv", encoding="latin-1")

# Keep only the required columns
df = df[['v1', 'v2']]
df.columns = ['label', 'text']

df.head()

  label                                               text
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [26]:
#1. Display the first 5 samples

print("First 5 Text Samples:\n")
print(df[['text']].head())

First 5 Text Samples:

                                                text
0  Go until jurong point, crazy.. Available only ...
1                      Ok lar... Joking wif u oni...
2  Free entry in 2 a wkly comp to win FA Cup fina...
3  U dun say so early hor... U c already then say...
4  Nah I don't think he goes to usf, he lives aro...

In [27]:
#2. Length of each text

df['text_length'] = df['text'].apply(len)
print(df[['text', 'text_length']].head())

                                                text  text_length
0  Go until jurong point, crazy.. Available only ...          111
1                      Ok lar... Joking wif u oni...           29
2  Free entry in 2 a wkly comp to win FA Cup fina...          155
3  U dun say so early hor... U c already then say...           49
4  Nah I don't think he goes to usf, he lives aro...           61

In [28]:
#3. Identify common issues in raw text

for i in range(5):
    print(f"\nSample {i+1}")
    print(df.loc[i, 'text'])

Sample 1
Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...

Sample 2
Ok lar... Joking wif u oni...

Sample 3
Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's

Sample 4
U dun say so early hor... U c already then say...

Sample 5
Nah I don't think he goes to usf, he lives around here though

### Common Issues Found in Raw Text

- Presence of uppercase and lowercase letters.
- Punctuation marks such as commas, periods and exclamation marks.
- Numbers present in some messages.
- Multiple spaces in a few messages.
- URLs and email addresses may appear.
- Special characters and symbols.

In [29]:
#Task 2: Basic Text Cleaning
import string
import re

def basic_clean(text):
    # Convert to lowercase
    text = text.lower()
    # Remove punctuation
    text = text.translate(str.maketrans('', '', string.punctuation))
    # Remove numbers
    text = re.sub(r'\d+', '', text)
    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

In [30]:
#applying

df['clean_text_basic'] = df['text'].apply(basic_clean)

#comparing original vs cleaned text:

df[['text', 'clean_text_basic']].head(10)

,text,clean_text_basic
0,"Go until jurong point, crazy.. Available only ...",go until jurong point crazy available only in ...
1,Ok lar... Joking wif u oni...,ok lar joking wif u oni
2,Free entry in 2 a wkly comp to win FA Cup fina...,free entry in a wkly comp to win fa cup final ...
3,U dun say so early hor... U c already then say...,u dun say so early hor u c already then say
4,"Nah I don't think he goes to usf, he lives aro...",nah i dont think he goes to usf he lives aroun...
5,FreeMsg Hey there darling it's been 3 week's n...,freemsg hey there darling its been weeks now a...
6,Even my brother is not like to speak with me. ...,even my brother is not like to speak with me t...
7,As per your request 'Melle Melle (Oru Minnamin...,as per your request melle melle oru minnaminun...
8,WINNER!! As a valued network customer you have...,winner as a valued network customer you have b...
9,Had your mobile 11 months or more? U R entitle...,had your mobile months or more u r entitled to...

In [31]:
#Task 3: Removing Noise

def advanced_clean(text):

    # Convert to lowercase
    text = text.lower()
    # Remove URLs
    text = re.sub(r'https?://\S+|www\.\S+', '', text)
    # Remove email addresses
    text = re.sub(r'\S+@\S+', '', text)
    # Remove HTML tags
    text = re.sub(r'<.*?>', '', text)
    # Remove numbers
    text = re.sub(r'\d+', '', text)
    # Remove punctuation and special characters
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text)

    return text.strip()

In [32]:
#Apply the function
df["clean_text_advanced"] = df["text"].apply(advanced_clean)

#Comparing the results

df[["text", "clean_text_basic", "clean_text_advanced"]].head(10)

,text,clean_text_basic,clean_text_advanced
0,"Go until jurong point, crazy.. Available only ...",go until jurong point crazy available only in ...,go until jurong point crazy available only in ...
1,Ok lar... Joking wif u oni...,ok lar joking wif u oni,ok lar joking wif u oni
2,Free entry in 2 a wkly comp to win FA Cup fina...,free entry in a wkly comp to win fa cup final ...,free entry in a wkly comp to win fa cup final ...
3,U dun say so early hor... U c already then say...,u dun say so early hor u c already then say,u dun say so early hor u c already then say
4,"Nah I don't think he goes to usf, he lives aro...",nah i dont think he goes to usf he lives aroun...,nah i dont think he goes to usf he lives aroun...
5,FreeMsg Hey there darling it's been 3 week's n...,freemsg hey there darling its been weeks now a...,freemsg hey there darling its been weeks now a...
6,Even my brother is not like to speak with me. ...,even my brother is not like to speak with me t...,even my brother is not like to speak with me t...
7,As per your request 'Melle Melle (Oru Minnamin...,as per your request melle melle oru minnaminun...,as per your request melle melle oru minnaminun...
8,WINNER!! As a valued network customer you have...,winner as a valued network customer you have b...,winner as a valued network customer you have b...
9,Had your mobile 11 months or more? U R entitle...,had your mobile months or more u r entitled to...,had your mobile months or more u r entitled to...

In [33]:
nltk.download('punkt_tab')

#Task 4: Remove Stopwords

stop_words = set(stopwords.words("english"))
def remove_stopwords(text):
    words = word_tokenize(text)
    filtered_words = []
    for word in words:
        if word not in stop_words:
            filtered_words.append(word)

    return " ".join(filtered_words)
#applying and comparing:

df["text_no_stopwords"] = df["clean_text_advanced"].apply(remove_stopwords)
df[["clean_text_advanced", "text_no_stopwords"]].head(10)

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

,clean_text_advanced,text_no_stopwords
0,go until jurong point crazy available only in ...,go jurong point crazy available bugis n great ...
1,ok lar joking wif u oni,ok lar joking wif u oni
2,free entry in a wkly comp to win fa cup final ...,free entry wkly comp win fa cup final tkts st ...
3,u dun say so early hor u c already then say,u dun say early hor u c already say
4,nah i dont think he goes to usf he lives aroun...,nah dont think goes usf lives around though
5,freemsg hey there darling its been weeks now a...,freemsg hey darling weeks word back id like fu...
6,even my brother is not like to speak with me t...,even brother like speak treat like aids patent
7,as per your request melle melle oru minnaminun...,per request melle melle oru minnaminunginte nu...
8,winner as a valued network customer you have b...,winner valued network customer selected receiv...
9,had your mobile months or more u r entitled to...,mobile months u r entitled update latest colou...

In [34]:
#Task 5: Repeated Characters & Slang

slang_dict = {
    "u": "you",
    "ur": "your",
    "gr8": "great",
    "luv": "love",
    "msg": "message",
    "pls": "please",
    "thx": "thanks"
}

def normalize_text(text):

    # Replace repeated characters
    text = re.sub(r'(.)\1{2,}', r'\1', text)

    words = []

    for word in text.split():
        words.append(slang_dict.get(word, word))

    return " ".join(words)

#applying and comparing

df["normalized_text"] = df["text_no_stopwords"].apply(normalize_text)
df[["text_no_stopwords", "normalized_text"]].head(10)

,text_no_stopwords,normalized_text
0,go jurong point crazy available bugis n great ...,go jurong point crazy available bugis n great ...
1,ok lar joking wif u oni,ok lar joking wif you oni
2,free entry wkly comp win fa cup final tkts st ...,free entry wkly comp win fa cup final tkts st ...
3,u dun say early hor u c already say,you dun say early hor you c already say
4,nah dont think goes usf lives around though,nah dont think goes usf lives around though
5,freemsg hey darling weeks word back id like fu...,freemsg hey darling weeks word back id like fu...
6,even brother like speak treat like aids patent,even brother like speak treat like aids patent
7,per request melle melle oru minnaminunginte nu...,per request melle melle oru minnaminunginte nu...
8,winner valued network customer selected receiv...,winner valued network customer selected receiv...
9,mobile months u r entitled update latest colou...,mobile months you r entitled update latest col...

In [35]:
#Task 6: Tokenization

#Word Tokenization
print("Word Tokenization (First 3 Samples)\n")

for i in range(3):
    print(f"Sample {i+1}")
    print(word_tokenize(df.loc[i, "normalized_text"]))
    print("-"*60)

#Sentence Tokenization
print("Sentence Tokenization (First 3 Samples)\n")

for i in range(3):
    print(f"Sample {i+1}")
    print(sent_tokenize(df.loc[i, "text"]))
    print("-"*60)

Word Tokenization (First 3 Samples)

Sample 1
['go', 'jurong', 'point', 'crazy', 'available', 'bugis', 'n', 'great', 'world', 'la', 'e', 'buffet', 'cine', 'got', 'amore', 'wat']
------------------------------------------------------------
Sample 2
['ok', 'lar', 'joking', 'wif', 'you', 'oni']
------------------------------------------------------------
Sample 3
['free', 'entry', 'wkly', 'comp', 'win', 'fa', 'cup', 'final', 'tkts', 'st', 'may', 'text', 'fa', 'receive', 'entry', 'questionstd', 'txt', 'ratetcs', 'apply', 'overs']
------------------------------------------------------------
Sentence Tokenization (First 3 Samples)

Sample 1
['Go until jurong point, crazy..', 'Available only in bugis n great world la e buffet... Cine there got amore wat...']
------------------------------------------------------------
Sample 2
['Ok lar...', 'Joking wif u oni...']
------------------------------------------------------------
Sample 3
['Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005.', "Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"]
------------------------------------------------------------

In [36]:
#Task 7: Stemming
stemmer = PorterStemmer()
sample_text = df.loc[0, "normalized_text"]

words = word_tokenize(sample_text)

stemmed_words = [stemmer.stem(word) for word in words]

comparison = pd.DataFrame({
    "Original Word": words,
    "Stemmed Word": stemmed_words
})

comparison

   Original Word Stemmed Word
0             go           go
1         jurong       jurong
2          point        point
3          crazy        crazi
4      available        avail
5          bugis         bugi
6              n            n
7          great        great
8          world        world
9             la           la
10             e            e
11        buffet       buffet
12          cine         cine
13           got          got
14         amore         amor
15           wat          wat

In [37]:
#Task 8: Lemmatization

lemmatizer = WordNetLemmatizer()
lemmatized_words = [lemmatizer.lemmatize(word) for word in words]

comparison = pd.DataFrame({
    "Original Word": words,
    "Stemmed": stemmed_words,
    "Lemmatized": lemmatized_words
})

comparison

   Original Word Stemmed Lemmatized
0             go      go         go
1         jurong  jurong     jurong
2          point   point      point
3          crazy   crazi      crazy
4      available   avail  available
5          bugis    bugi      bugis
6              n       n          n
7          great   great      great
8          world   world      world
9             la      la         la
10             e       e          e
11        buffet  buffet     buffet
12          cine    cine       cine
13           got     got        got
14         amore    amor      amore
15           wat     wat        wat

In [38]:
#Task 9: Final NLP Pipeline

def nlp_preprocess(text):
    # Advanced Cleaning
    text = advanced_clean(text)
    # Remove Stopwords
    text = remove_stopwords(text)
    # Normalize Text
    text = normalize_text(text)
    # Tokenization
    tokens = word_tokenize(text)
    # Lemmatization
    tokens = [lemmatizer.lemmatize(word) for word in tokens]

    return " ".join(tokens)

#applying and showing the output

df["final_clean_text"] = df["text"].apply(nlp_preprocess)
df[["text", "final_clean_text"]].head(10)

#saving the processed dataset

df.to_csv("processed_sms_dataset.csv", index=False)

print("Processed dataset saved successfully.")

Processed dataset saved successfully.

Task 10: Observations
Observations & Insights

1. Difference between Basic and Advanced Cleaning

Basic text cleaning removes common formatting issues such as uppercase letters, punctuation, numbers, and extra spaces. Advanced cleaning goes a step further by removing URLs, email addresses, HTML tags, and special characters, producing cleaner and more consistent text for NLP tasks.

2. Why Lemmatization is Preferred Over Stemming

Stemming simply removes word endings and may generate incomplete words such as studies → studi. Lemmatization uses vocabulary and language rules to convert words into their proper dictionary form, such as studies → study. This preserves the meaning of the text and is generally preferred for NLP applications.

3. Importance of Preprocessing in NLP Models

Text preprocessing removes unwanted noise, standardizes text, and reduces unnecessary variations in words. This helps NLP models focus on meaningful information, improves model accuracy, and reduces computational complexity during training.